artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/revv2703/Summlytics/raw/main/dataset/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  FILE_STATUS: artifacts/data_validation/file_status.json #YOU HAVE IT IN JSON
  ALL_REQUIRED_FILES: ["train", "test", "validation"]


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail


train_model:
  root_dir: artifacts/train_model
  data_path: artifacts/data_transformation/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail


evaluate_model:
  root_dir: artifacts/evaluate_model
  data_path: artifacts/data_transformation/samsum_dataset
  model_path: artifacts/train_model/pegasus-samsum-model
  tokenizer_path: artifacts/train_model/pegasus-samsum-tokenizer
  metric_file_name: artifacts/evaluate_model/metrics.csv